# Generated by Django 4.2.4 on 2025-12-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0002_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='clientApp.client'),
        ),
    ]
