# Generated by Django 4.2.4 on 2025-12-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0003_system_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
    ]
