# Generated by Django 4.2.4 on 2025-12-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0004_rename_first_name_client_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='client',
        ),
    ]
