# Generated by Django 4.2.4 on 2025-12-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
